version: '3'

services:

    python:
        container_name: python_flask
        build:
            context: .
            dockerfile: ./python/Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - .:/home/python
        ports:
            - 8000:8000